# Estagio 1 - base
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
RUN mkdir /app
WORKDIR /app # Diretorio padrão de trabalho
EXPOSE 80/tcp

# Estagio 2 - publish
FROM microsoft/dotnet:2.1-sdk AS publish
WORKDIR /app
COPY mvc1.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o dist

# Estagio 3 - final
FROM base AS final
WORKDIR /dist
COPY --from=publish /app/dist .
ENTRYPOINT ["dotnet", "mvc1.dll"]