version: "3"

volumes:
  produtosdata:

networks:
  frontend:
  backend:

services: 
  mysql:
    image: "mysql:5.7"
    volumes:
      - produtosdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d #Retirado da documentação da imagem do mysql
    networks:
      - backend
    environment: 
      - MYSQL_ROOT_PASSWORD=numsey
      - bind-address=0.0.0.0

  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    networks: 
      - backend
      - frontend
    ports:
      - 5000:80
    environment:
      - DBHOST=mysql
    depends_on:
      - mysql